import "@radix-ui/themes/styles.css";
import "./css/theme-config.css";
import "./css/globals.css";

import { ReactNode } from "react";

import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";

import NavBar from "@/components/NavBar";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={inter.variable}>
      <body suppressHydrationWarning={true}>
        <Theme>
          <NavBar />
          <main className="p-5">
            <ReactQueryProvider>{children}</ReactQueryProvider>
            <Toaster position="top-right" richColors />
          </main>
        </Theme>
      </body>
    </html>
  );
}
